---
- hosts: localhost
  tasks:
    - name: Includ user vars
      include_vars: "user_variable.yml"
    - name: Includ default vars
      include_vars: "default_variable.yml"
    # - name: Install operator
    #   include: install_operator.yaml
    