apiVersion: federatorai.containers.ai/v1alpha1
kind: AlamedaService
metadata:
  name: my-alamedaservice
  namespace: federatorai
spec:
  keycode:
    codeNumber: NYQS3-WCZCI-ZOR4R-RYTBD-EC7JG-UNCGA
  selfDriving: false             ## to enable resource self-orchestration of the deployed Alameda components
                                 ## it is recommended NOT to use ephemeral data storage for Alameda influxdb component when self-Driving is enabled
  enableExecution: false
  enableGui: false
  version: latest               ## for Alameda components. (exclude grafana and influxdb)
  storages:                     ## see following details for where it is used in each component
    - usage: log                ## storage setting for log
      type: ephemeral           ## ephemeral means emptyDir{}
    - usage: data
      type: ephemeral
#    - usage: data               ## storage setting for data
#      type: pvc                 ## pvc means PersistentVolumeClaim
#      size: 10Gi                ## mandatory when type=pvc
#      class: "normal"           ## mandatory when type=pvc
